-- MySQL Script generated by MySQL Workbench
-- Sun Feb  4 18:10:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema checkmate
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema checkmate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `checkmate` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `checkmate` ;

-- -----------------------------------------------------
-- Table `checkmate`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkmate`.`card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cardNumber` VARCHAR(16) NOT NULL,
  `cvv` INT NOT NULL,
  `date` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `checkmate`.`station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkmate`.`station` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `town` VARCHAR(150) NOT NULL,
  `address` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `checkmate`.`shift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkmate`.`shift` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `station_id` INT NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `is_first` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shift_station1_idx` (`station_id` ASC) VISIBLE,
  CONSTRAINT `fk_shift_station1`
    FOREIGN KEY (`station_id`)
    REFERENCES `checkmate`.`station` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `checkmate`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkmate`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `isEmployee` TINYINT NULL DEFAULT '0',
  `isAdmin` TINYINT NULL DEFAULT '0',
  `balance` DECIMAL(10,2) NULL DEFAULT '0.00',
  `card_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `checkmate`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkmate`.`test` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` TIME NOT NULL,
  `result` TINYINT NULL DEFAULT NULL,
  `pacient_id` INT NOT NULL,
  `shift_id` INT NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `test_type` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_test_user1_idx` (`pacient_id` ASC) VISIBLE,
  INDEX `fk_test_shift1_idx` (`shift_id` ASC) VISIBLE,
  CONSTRAINT `fk_test_shift1`
    FOREIGN KEY (`shift_id`)
    REFERENCES `checkmate`.`shift` (`id`),
  CONSTRAINT `fk_test_user1`
    FOREIGN KEY (`pacient_id`)
    REFERENCES `checkmate`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 114
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `checkmate`.`user_has_shift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkmate`.`user_has_shift` (
  `user_id` INT NOT NULL,
  `shift_id` INT NOT NULL,
  `isConfirmed` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`user_id`, `shift_id`),
  INDEX `fk_user_has_shift_shift1_idx` (`shift_id` ASC) VISIBLE,
  INDEX `fk_user_has_shift_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_shift_shift1`
    FOREIGN KEY (`shift_id`)
    REFERENCES `checkmate`.`shift` (`id`),
  CONSTRAINT `fk_user_has_shift_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `checkmate`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `checkmate`.`worker_codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkmate`.`worker_codes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workercode` VARCHAR(60) NULL DEFAULT NULL,
  `isActive` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
